Assalamualaikum,
Saya akan mencoba mengerjakan Datjer dengan ikhlas dan tabah
Mari kita mulai dari awal lagi yaitu 'nyecrape data'

---

Web Scraping, dilakukan dengan mengambil data dari portal berita online yaitu : Detik.Com

In [ ]:
import requests as req
from bs4 import BeautifulSoup
import csv
import pandas as pd

## **Detik.Com Scrapping (3600++ data)**


---

File 1 = range (1, 55)
File 2 = range (56, 110)
File 3 = range (111, 166)
File 4 = range (167, 220)
File 5 = range (221, 276)
File 6 = range (277, 331)
File 7 = range (332, 386)
File 8 = range (387, 441)

Pengambilan data

In [ ]:
data = []

for page in range(167, 220):
    url = f'https://www.detik.com/search/searchall?query=kecelakaan+lalu+lintas&siteid=2&sortby=time&sorttime=3&fromdatex=01/04/2022&todatex=31/03/2023&page={page}'
    r = req.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')
    for article in soup.find_all('article'):
        tautan = article.find('a')['href']
        caption = article.find('p').text
        response = req.get(tautan)
        soup = BeautifulSoup(response.text, 'html.parser')

        # Mengambil judul artikel
        judul = soup.find('h1', {'class': 'detail__title'})
        if judul:
          judul = judul.text
          judul = judul.replace('\n','')
        else :
          judul = None

        # Mengambil tanggal publikasi
        tanggal = soup.find('div', {'class': 'detail__date'})
        if tanggal:
          tanggal = tanggal.text
        else :
          tanggal = tanggal

        # Mengambil Penulis Artikel
        writer = soup.find('div', {'class': 'detail__author'})
        if writer:
            writer = writer.text
        else:
            writer = None

        # Mengambil label
        label = soup.find('span', {'class': 'detail__label'})
        if label:
            label = label.text
        else:
            label = None

        # Mengambil kota
        city = soup.find('strong')
        if city:
            city = city.text
        else:
            city = None

        # Mengambil descripsi lengkap
        content = soup.find('div', {'class': 'detail__body-text'})
        if content :
          content = content.text
          content = content.replace('\n', '').replace('\r','').replace('ADVERTISEMENT','').replace('SCROLL TO RESUME CONTENT', '')
        else :
          content = None

        # Menambahkan data ke list
        data.append([judul, tanggal, writer, label, city, content, tautan])

columns = ['Judul', 'Tanggal', 'Penulis', 'Label', 'Kota', 'Deskripsi', 'Url']
df = pd.DataFrame(data, columns=columns)
print(df)

                                                 Judul  \
0            8 Fakta Kerusuhan Dogiyai Berujung 6 K...
1            Truk Mogok di Km 12 Tol Jagorawi, Lali...
2            Tanda Tanya Nasib Ibu dan 2 Anaknya Hi...
3            Respons KAI Usai Kereta Tabrak Mobil y...
4            Reuni Anak Pesantren Berujung Kecelaka...
..                                                 ...
472          Truk Tangki Seruduk Pemotor-Warung di ...
473          Truk Tangki Terguling hingga Seruduk W...
474          Truk Tangki Muat Solar Terguling hingg...
475          Alasan Hotman Paris Buka 911 untuk Mas...
476          Mobil Avanza Ringsek Tertabrak KA di S...

                           Tanggal                          Penulis  \
0     Senin, 14 Nov 2022 09:00 WIB       Tim detikcom - detikSulsel
1     Senin, 14 Nov 2022 08:40 WIB  Rizky Adha Mahendra - detikNews
2     Senin, 14 Nov 2022 08:01 WIB       Tim detikcom - detikSulsel
3     Senin, 14 Nov 2022 01:00 WIB         Wisma Putra - detikJabar
4    Minggu, 13 Nov 2022 19:30 WIB    Faizal Amiruddin - detikJabar
..                             ...                              ...
472  Minggu, 25 Sep 2022 15:44 WIB        Ardian Fanani - detikNews
473  Minggu, 25 Sep 2022 15:17 WIB       Ardian Fanani - detikJatim
474  Minggu, 25 Sep 2022 13:50 WIB       Ardian Fanani - detikJatim
475  Minggu, 25 Sep 2022 13:15 WIB      Tim detikJatim - detikJatim
476  Minggu, 25 Sep 2022 12:50 WIB        Siti Fatimah - detikJabar

           Label         Kota  \
0    detikSulsel      Dogiyai
1      detikNews      Jakarta
2    detikSulsel      Dogiyai
3     detikJabar  Tasikmalaya
4     detikJabar  Tasikmalaya
..           ...          ...
472    detikNews   Banyuwangi
473   detikJatim   Banyuwangi
474   detikJatim   Banyuwangi
475   detikJatim     Surabaya
476   detikJabar     Sukabumi

                                             Deskripsi  \
0    Dogiyai -  Peristiwa balita bernama Noldi Goo ...
1    Jakarta - Sebuah truk mogok di Km 12 Tol Jagor...
2    Dogiyai -  Kerusuhan di Kabupaten Dogiyai, Pap...
3    Tasikmalaya - Tiga orang tewas dalam insiden k...
4    Tasikmalaya - Kecelakaan mobil tertabrak keret...
..                                                 ...
472  Banyuwangi - Kecelakaan maut truk tangki menab...
473  Banyuwangi - Kecelakaan maut terjadi di lampu ...
474  Banyuwangi - Sebuah truk tangki muatan BBM ter...
475  Surabaya -  Hotman Paris Hutapea menggelar aca...
476  Sukabumi - Kecelakaan lalu lintas antara mobil...

                                                   Url
0    https://www.detik.com/sulsel/berita/d-6404357/...
1    https://news.detik.com/berita/d-6404510/truk-m...
2    https://www.detik.com/sulsel/hukum-dan-krimina...
3    https://www.detik.com/jabar/berita/d-6403718/r...
4    https://www.detik.com/jabar/berita/d-6403465/r...
..                                                 ...
472  https://news.detik.com/berita/d-6311268/truk-t...
473  https://www.detik.com/jatim/berita/d-6311237/t...
474  https://www.detik.com/jatim/berita/d-6311152/t...
475  https://www.detik.com/jatim/hukum-dan-kriminal...
476  https://www.detik.com/jabar/berita/d-6311063/m...

[477 rows x 7 columns]

## **Kompas.Com Scaraping ()**

In [ ]:
data_kompas = []

for page in range (3, 28) :
  url = f'https://www.kompas.com/tag/kecelakaan-lalu-lintas?page={page}'
  r = req.get(url)
  soup = BeautifulSoup(r.content, 'html.parser')
  articles = soup.find_all("div", class_="article__list clearfix")
  for article in articles:
    tautan = article.find('a')['href']
    response = req.get(tautan)
    soup = BeautifulSoup(response.content, 'html.parser')

    judul = soup.find("h1", class_="read__title")
    if judul:
        judul = judul.text
        tanggal = soup.find("div", class_="read__time").text
        writer = soup.find("div", class_="read__credit__item").find("a").text
        label = soup.find("ul", class_="breadcrumb__wrap")
        kategori = label.find_all("a")[-1].text.strip()
        city = soup.find("div", class_="read__content").find("strong").text
        if city:
            city.strip()
        else :
            city2 = soup.find("div", class_="read__content").find("a").text
            city = city2
        content = soup.find("div", class_="read__content").text
    else :
        judul = None
        tanggal = None
        writer = None
        kategori = None
        city = None
        content = None

    # Menambahkan data ke list
    data_kompas.append({'Judul': judul, 'Tanggal': tanggal, 'Penulis': writer, 'Label': kategori, 'Kota': city, 'Content': content, 'Url': tautan})

    print(tanggal)

## **SindoNews.Com**


---

Gk jadi, gk enakeun webnya

## **Membuat CSV**

---

In [ ]:
df.to_csv('detik.com_fixnews(4).csv')
df

,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,8 Fakta Kerusuhan Dogiyai Berujung 6 K...,"Senin, 14 Nov 2022 09:00 WIB",Tim detikcom - detikSulsel,detikSulsel,Dogiyai,Dogiyai - Peristiwa balita bernama Noldi Goo ...,https://www.detik.com/sulsel/berita/d-6404357/...
1,"Truk Mogok di Km 12 Tol Jagorawi, Lali...","Senin, 14 Nov 2022 08:40 WIB",Rizky Adha Mahendra - detikNews,detikNews,Jakarta,Jakarta - Sebuah truk mogok di Km 12 Tol Jagor...,https://news.detik.com/berita/d-6404510/truk-m...
2,Tanda Tanya Nasib Ibu dan 2 Anaknya Hi...,"Senin, 14 Nov 2022 08:01 WIB",Tim detikcom - detikSulsel,detikSulsel,Dogiyai,"Dogiyai - Kerusuhan di Kabupaten Dogiyai, Pap...",https://www.detik.com/sulsel/hukum-dan-krimina...
3,Respons KAI Usai Kereta Tabrak Mobil y...,"Senin, 14 Nov 2022 01:00 WIB",Wisma Putra - detikJabar,detikJabar,Tasikmalaya,Tasikmalaya - Tiga orang tewas dalam insiden k...,https://www.detik.com/jabar/berita/d-6403718/r...
4,Reuni Anak Pesantren Berujung Kecelaka...,"Minggu, 13 Nov 2022 19:30 WIB",Faizal Amiruddin - detikJabar,detikJabar,Tasikmalaya,Tasikmalaya - Kecelakaan mobil tertabrak keret...,https://www.detik.com/jabar/berita/d-6403465/r...
...,...,...,...,...,...,...,...
472,Truk Tangki Seruduk Pemotor-Warung di ...,"Minggu, 25 Sep 2022 15:44 WIB",Ardian Fanani - detikNews,detikNews,Banyuwangi,Banyuwangi - Kecelakaan maut truk tangki menab...,https://news.detik.com/berita/d-6311268/truk-t...
473,Truk Tangki Terguling hingga Seruduk W...,"Minggu, 25 Sep 2022 15:17 WIB",Ardian Fanani - detikJatim,detikJatim,Banyuwangi,Banyuwangi - Kecelakaan maut terjadi di lampu ...,https://www.detik.com/jatim/berita/d-6311237/t...
474,Truk Tangki Muat Solar Terguling hingg...,"Minggu, 25 Sep 2022 13:50 WIB",Ardian Fanani - detikJatim,detikJatim,Banyuwangi,Banyuwangi - Sebuah truk tangki muatan BBM ter...,https://www.detik.com/jatim/berita/d-6311152/t...
475,Alasan Hotman Paris Buka 911 untuk Mas...,"Minggu, 25 Sep 2022 13:15 WIB",Tim detikJatim - detikJatim,detikJatim,Surabaya,Surabaya - Hotman Paris Hutapea menggelar aca...,https://www.detik.com/jatim/hukum-dan-kriminal...
476,Mobil Avanza Ringsek Tertabrak KA di S...,"Minggu, 25 Sep 2022 12:50 WIB",Siti Fatimah - detikJabar,detikJabar,Sukabumi,Sukabumi - Kecelakaan lalu lintas antara mobil...,https://www.detik.com/jabar/berita/d-6311063/m...



---

In [ ]:
with open('kompas.com_fixeddata.csv', mode='w', newline='', encoding='utf-8') as file:
    writer = csv.DictWriter(file, fieldnames=['Judul', 'Tanggal', 'Penulis', 'Label', 'Kota', 'Content', 'Url'])
    writer.writeheader()
    for d in data_kompas:
        writer.writerow(d)

## **Download CSV**

---

In [ ]:
from google.colab import files
files.download('detik.com_fixnews(4).csv')

## **Liat Tabel Data Mentah**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving detik.com_concatenated.csv to detik.com_concatenated (1).csv

In [ ]:
df

,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,8 Fakta Kerusuhan Dogiyai Berujung 6 K...,"Senin, 14 Nov 2022 09:00 WIB",Tim detikcom - detikSulsel,detikSulsel,Dogiyai,Dogiyai - Peristiwa balita bernama Noldi Goo ...,https://www.detik.com/sulsel/berita/d-6404357/...
1,"Truk Mogok di Km 12 Tol Jagorawi, Lali...","Senin, 14 Nov 2022 08:40 WIB",Rizky Adha Mahendra - detikNews,detikNews,Jakarta,Jakarta - Sebuah truk mogok di Km 12 Tol Jagor...,https://news.detik.com/berita/d-6404510/truk-m...
2,Tanda Tanya Nasib Ibu dan 2 Anaknya Hi...,"Senin, 14 Nov 2022 08:01 WIB",Tim detikcom - detikSulsel,detikSulsel,Dogiyai,"Dogiyai - Kerusuhan di Kabupaten Dogiyai, Pap...",https://www.detik.com/sulsel/hukum-dan-krimina...
3,Respons KAI Usai Kereta Tabrak Mobil y...,"Senin, 14 Nov 2022 01:00 WIB",Wisma Putra - detikJabar,detikJabar,Tasikmalaya,Tasikmalaya - Tiga orang tewas dalam insiden k...,https://www.detik.com/jabar/berita/d-6403718/r...
4,Reuni Anak Pesantren Berujung Kecelaka...,"Minggu, 13 Nov 2022 19:30 WIB",Faizal Amiruddin - detikJabar,detikJabar,Tasikmalaya,Tasikmalaya - Kecelakaan mobil tertabrak keret...,https://www.detik.com/jabar/berita/d-6403465/r...
...,...,...,...,...,...,...,...
472,Truk Tangki Seruduk Pemotor-Warung di ...,"Minggu, 25 Sep 2022 15:44 WIB",Ardian Fanani - detikNews,detikNews,Banyuwangi,Banyuwangi - Kecelakaan maut truk tangki menab...,https://news.detik.com/berita/d-6311268/truk-t...
473,Truk Tangki Terguling hingga Seruduk W...,"Minggu, 25 Sep 2022 15:17 WIB",Ardian Fanani - detikJatim,detikJatim,Banyuwangi,Banyuwangi - Kecelakaan maut terjadi di lampu ...,https://www.detik.com/jatim/berita/d-6311237/t...
474,Truk Tangki Muat Solar Terguling hingg...,"Minggu, 25 Sep 2022 13:50 WIB",Ardian Fanani - detikJatim,detikJatim,Banyuwangi,Banyuwangi - Sebuah truk tangki muatan BBM ter...,https://www.detik.com/jatim/berita/d-6311152/t...
475,Alasan Hotman Paris Buka 911 untuk Mas...,"Minggu, 25 Sep 2022 13:15 WIB",Tim detikJatim - detikJatim,detikJatim,Surabaya,Surabaya - Hotman Paris Hutapea menggelar aca...,https://www.detik.com/jatim/hukum-dan-kriminal...
476,Mobil Avanza Ringsek Tertabrak KA di S...,"Minggu, 25 Sep 2022 12:50 WIB",Siti Fatimah - detikJabar,detikJabar,Sukabumi,Sukabumi - Kecelakaan lalu lintas antara mobil...,https://www.detik.com/jabar/berita/d-6311063/m...

## Menggabungkan CSV

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving detik.com_fixnews(1).csv to detik.com_fixnews(1).csv
Saving detik.com_fixnews(2).csv to detik.com_fixnews(2).csv
Saving detik.com_fixnews(3).csv to detik.com_fixnews(3).csv
Saving detik.com_fixnews(4).csv to detik.com_fixnews(4) (1).csv
Saving detik.com_fixnews(5).csv to detik.com_fixnews(5).csv
Saving detik.com_fixnews(6).csv to detik.com_fixnews(6).csv
Saving detik.com_fixnews(7).csv to detik.com_fixnews(7).csv
Saving detik.com_fixnews(8).csv to detik.com_fixnews(8).csv

In [ ]:
import pandas as pd

# Membaca masing-masing file CSV ke dalam data frame
df1 = pd.read_csv('detik.com_fixnews(1).csv')
df2 = pd.read_csv('detik.com_fixnews(2).csv')
df3 = pd.read_csv('detik.com_fixnews(3).csv')
df4 = pd.read_csv('detik.com_fixnews(4).csv')
df5 = pd.read_csv('detik.com_fixnews(5).csv')
df6 = pd.read_csv('detik.com_fixnews(6).csv')
df7 = pd.read_csv('detik.com_fixnews(7).csv')
df8 = pd.read_csv('detik.com_fixnews(8).csv')

# Menggabungkan keempat data frame menjadi satu data frame
df_concatenated = pd.concat([df1, df2, df3, df4, df5, df6, df7, df8])

# Menyimpan data frame yang sudah digabung menjadi satu ke dalam file CSV
df_concatenated.to_csv('detik.com_fixcombined.csv', index=False)

# Download file CSV yang sudah digabung
from google.colab import files
files.download('detik.com_fixcombined.csv')

## ***Phase 2***

---

## **Data Cleaning**

In [ ]:
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python

import numpy as np # pemakaian linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from tqdm import tqdm # looping

import warnings
warnings.filterwarnings('ignore')

In [ ]:
from google.colab import files
uploaded = files.upload()

In [ ]:
import io
df = pd.read_csv(io.StringIO(uploaded['detik.com_fixcombined.csv'].decode('utf-8')))
# io.StringIO, ngubah semua character yang ada di filenya menjadi string jadi data ini text-only data
# decode('utf-8') ini buat decoder kode universal untuk internasionalisasi dan mampu mengodekan seluruh set karakter Unicode
df

In [ ]:
df.shape # check total row + column

In [ ]:
df.columns # check field

Index(['Judul', 'Tanggal', 'Penulis', 'Label', 'Kota', 'Deskripsi', 'Url'], dtype='object')

In [ ]:
df = df.dropna()
df.to_csv('detik.com_fixcombined_nulldelete.csv', index=False)
df

,Unnamed: 0,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,0,Jabar Hari Ini: Sakit Hati Dua Pemain ...,"Kamis, 30 Mar 2023 22:00 WIB",Tim detikJabar - detikJabar,detikJabar,Bandung,Bandung - Beragam peristiwa terjadi di Jawa Ba...,https://www.detik.com/jabar/berita/d-6646815/j...
1,1,Waka DPRD Tanjabbar Tinggalkan TKP Usa...,"Kamis, 30 Mar 2023 21:44 WIB",Ferdi Almunanda - detikSumut,detikSumut,Jambi,Jambi - ABG bernama Siti Nuanisa (17) tewas us...,https://www.detik.com/sumut/berita/d-6647430/w...
2,2,Jalan Raya Casablanca Jakarta Macet di...,"Kamis, 30 Mar 2023 18:49 WIB",Jabbar Ramdhani - detikNews,detikNews,Jakarta,Jakarta - Kemacetan terjadi di Jalan Raya Casa...,https://news.detik.com/berita/d-6647094/jalan-...
3,3,Pemotor Mabuk Tabrak 3 Anggota Satpol ...,"Kamis, 30 Mar 2023 17:59 WIB",Deny Prastyo - detikJatim,detikJatim,Surabaya,Surabaya - Polisi telah menetapkan pemotor ber...,https://www.detik.com/jatim/hukum-dan-kriminal...
4,4,Fakta Viral Pria Tergeletak dengan Waj...,"Kamis, 30 Mar 2023 14:04 WIB",Rifat Alhamidi - detikJabar,detikJabar,Bandung,Bandung - Polisi memastikan video viral yang m...,https://www.detik.com/jabar/hukum-dan-kriminal...
...,...,...,...,...,...,...,...,...
3146120,481,Fakta-fakta Kecelakaan Adu Banteng Tew...,"Jumat, 01 Apr 2022 19:54 WIB",Tim detikJateng - detikJateng,detikJateng,Solo,Solo - Kecelakaan maut antara truk dengan mobi...,https://www.detik.com/jateng/berita/d-6012255/...
3146121,482,Jasa Raharja Pati Cairkan Santunan 3 K...,"Jumat, 01 Apr 2022 19:52 WIB",Angling Adhitya Purbaya - detikJateng,detikJateng,Semarang,Semarang - Kecelakaan adu banteng antara truk ...,https://www.detik.com/jateng/bisnis/d-6012252/...
3146122,483,"Jangan Lelet Apalagi Ngebut di Tol, Se...","Jumat, 01 Apr 2022 18:10 WIB",Tim detikcom - detikOto,detikOto,Jakarta,Jakarta - Batas kecepatan kendaraan di jalan s...,https://oto.detik.com/mobil/d-6012027/jangan-l...
3146123,484,Hyundai Ioniq 5 Tambah Daftar Mobil ya...,"Jumat, 01 Apr 2022 17:33 WIB",Dina Rayanti - detikOto,detikOto,Jakarta,"Jakarta - Produsen asal Korea Selatan, Hyundai...",https://oto.detik.com/mobil/d-6011922/hyundai-...
3146124,485,Detik-detik Kecelakaan Adu Banteng yan...,"Jumat, 01 Apr 2022 15:19 WIB",Tim detikcom - detikNews,detikNews,Pemalang,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...,https://news.detik.com/berita/d-6011711/detik-...

In [ ]:
df = df.drop(columns=['Unnamed: 0'])
df

,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,Jabar Hari Ini: Sakit Hati Dua Pemain ...,"Kamis, 30 Mar 2023 22:00 WIB",Tim detikJabar - detikJabar,detikJabar,Bandung,Bandung - Beragam peristiwa terjadi di Jawa Ba...,https://www.detik.com/jabar/berita/d-6646815/j...
1,Waka DPRD Tanjabbar Tinggalkan TKP Usa...,"Kamis, 30 Mar 2023 21:44 WIB",Ferdi Almunanda - detikSumut,detikSumut,Jambi,Jambi - ABG bernama Siti Nuanisa (17) tewas us...,https://www.detik.com/sumut/berita/d-6647430/w...
2,Jalan Raya Casablanca Jakarta Macet di...,"Kamis, 30 Mar 2023 18:49 WIB",Jabbar Ramdhani - detikNews,detikNews,Jakarta,Jakarta - Kemacetan terjadi di Jalan Raya Casa...,https://news.detik.com/berita/d-6647094/jalan-...
3,Pemotor Mabuk Tabrak 3 Anggota Satpol ...,"Kamis, 30 Mar 2023 17:59 WIB",Deny Prastyo - detikJatim,detikJatim,Surabaya,Surabaya - Polisi telah menetapkan pemotor ber...,https://www.detik.com/jatim/hukum-dan-kriminal...
4,Fakta Viral Pria Tergeletak dengan Waj...,"Kamis, 30 Mar 2023 14:04 WIB",Rifat Alhamidi - detikJabar,detikJabar,Bandung,Bandung - Polisi memastikan video viral yang m...,https://www.detik.com/jabar/hukum-dan-kriminal...
...,...,...,...,...,...,...,...
3146120,Fakta-fakta Kecelakaan Adu Banteng Tew...,"Jumat, 01 Apr 2022 19:54 WIB",Tim detikJateng - detikJateng,detikJateng,Solo,Solo - Kecelakaan maut antara truk dengan mobi...,https://www.detik.com/jateng/berita/d-6012255/...
3146121,Jasa Raharja Pati Cairkan Santunan 3 K...,"Jumat, 01 Apr 2022 19:52 WIB",Angling Adhitya Purbaya - detikJateng,detikJateng,Semarang,Semarang - Kecelakaan adu banteng antara truk ...,https://www.detik.com/jateng/bisnis/d-6012252/...
3146122,"Jangan Lelet Apalagi Ngebut di Tol, Se...","Jumat, 01 Apr 2022 18:10 WIB",Tim detikcom - detikOto,detikOto,Jakarta,Jakarta - Batas kecepatan kendaraan di jalan s...,https://oto.detik.com/mobil/d-6012027/jangan-l...
3146123,Hyundai Ioniq 5 Tambah Daftar Mobil ya...,"Jumat, 01 Apr 2022 17:33 WIB",Dina Rayanti - detikOto,detikOto,Jakarta,"Jakarta - Produsen asal Korea Selatan, Hyundai...",https://oto.detik.com/mobil/d-6011922/hyundai-...
3146124,Detik-detik Kecelakaan Adu Banteng yan...,"Jumat, 01 Apr 2022 15:19 WIB",Tim detikcom - detikNews,detikNews,Pemalang,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...,https://news.detik.com/berita/d-6011711/detik-...

In [ ]:
files.download('detik.com_fixcombined_nulldelete.csv')

In [ ]:
uploaded = files.upload()

Saving detik.com_fixcombined_nulldelete.csv to detik.com_fixcombined_nulldelete.csv

In [ ]:
df = pd.read_csv('detik.com_fixcombined_nulldelete.csv')
df

,Unnamed: 0,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,0,Jabar Hari Ini: Sakit Hati Dua Pemain ...,"Kamis, 30 Mar 2023 22:00 WIB",Tim detikJabar - detikJabar,detikJabar,Bandung,Bandung - Beragam peristiwa terjadi di Jawa Ba...,https://www.detik.com/jabar/berita/d-6646815/j...
1,1,Waka DPRD Tanjabbar Tinggalkan TKP Usa...,"Kamis, 30 Mar 2023 21:44 WIB",Ferdi Almunanda - detikSumut,detikSumut,Jambi,Jambi - ABG bernama Siti Nuanisa (17) tewas us...,https://www.detik.com/sumut/berita/d-6647430/w...
2,2,Jalan Raya Casablanca Jakarta Macet di...,"Kamis, 30 Mar 2023 18:49 WIB",Jabbar Ramdhani - detikNews,detikNews,Jakarta,Jakarta - Kemacetan terjadi di Jalan Raya Casa...,https://news.detik.com/berita/d-6647094/jalan-...
3,3,Pemotor Mabuk Tabrak 3 Anggota Satpol ...,"Kamis, 30 Mar 2023 17:59 WIB",Deny Prastyo - detikJatim,detikJatim,Surabaya,Surabaya - Polisi telah menetapkan pemotor ber...,https://www.detik.com/jatim/hukum-dan-kriminal...
4,4,Fakta Viral Pria Tergeletak dengan Waj...,"Kamis, 30 Mar 2023 14:04 WIB",Rifat Alhamidi - detikJabar,detikJabar,Bandung,Bandung - Polisi memastikan video viral yang m...,https://www.detik.com/jabar/hukum-dan-kriminal...
...,...,...,...,...,...,...,...,...
3674,481,Fakta-fakta Kecelakaan Adu Banteng Tew...,"Jumat, 01 Apr 2022 19:54 WIB",Tim detikJateng - detikJateng,detikJateng,Solo,Solo - Kecelakaan maut antara truk dengan mobi...,https://www.detik.com/jateng/berita/d-6012255/...
3675,482,Jasa Raharja Pati Cairkan Santunan 3 K...,"Jumat, 01 Apr 2022 19:52 WIB",Angling Adhitya Purbaya - detikJateng,detikJateng,Semarang,Semarang - Kecelakaan adu banteng antara truk ...,https://www.detik.com/jateng/bisnis/d-6012252/...
3676,483,"Jangan Lelet Apalagi Ngebut di Tol, Se...","Jumat, 01 Apr 2022 18:10 WIB",Tim detikcom - detikOto,detikOto,Jakarta,Jakarta - Batas kecepatan kendaraan di jalan s...,https://oto.detik.com/mobil/d-6012027/jangan-l...
3677,484,Hyundai Ioniq 5 Tambah Daftar Mobil ya...,"Jumat, 01 Apr 2022 17:33 WIB",Dina Rayanti - detikOto,detikOto,Jakarta,"Jakarta - Produsen asal Korea Selatan, Hyundai...",https://oto.detik.com/mobil/d-6011922/hyundai-...
3678,485,Detik-detik Kecelakaan Adu Banteng yan...,"Jumat, 01 Apr 2022 15:19 WIB",Tim detikcom - detikNews,detikNews,Pemalang,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...,https://news.detik.com/berita/d-6011711/detik-...

Menghapus kolom yang tak bernama

In [ ]:
df = df.drop(columns=['Unnamed: 0'])
df

,Judul,Tanggal,Penulis,Label,Kota,Deskripsi,Url
0,Jabar Hari Ini: Sakit Hati Dua Pemain ...,"Kamis, 30 Mar 2023 22:00 WIB",Tim detikJabar - detikJabar,detikJabar,Bandung,Bandung - Beragam peristiwa terjadi di Jawa Ba...,https://www.detik.com/jabar/berita/d-6646815/j...
1,Waka DPRD Tanjabbar Tinggalkan TKP Usa...,"Kamis, 30 Mar 2023 21:44 WIB",Ferdi Almunanda - detikSumut,detikSumut,Jambi,Jambi - ABG bernama Siti Nuanisa (17) tewas us...,https://www.detik.com/sumut/berita/d-6647430/w...
2,Jalan Raya Casablanca Jakarta Macet di...,"Kamis, 30 Mar 2023 18:49 WIB",Jabbar Ramdhani - detikNews,detikNews,Jakarta,Jakarta - Kemacetan terjadi di Jalan Raya Casa...,https://news.detik.com/berita/d-6647094/jalan-...
3,Pemotor Mabuk Tabrak 3 Anggota Satpol ...,"Kamis, 30 Mar 2023 17:59 WIB",Deny Prastyo - detikJatim,detikJatim,Surabaya,Surabaya - Polisi telah menetapkan pemotor ber...,https://www.detik.com/jatim/hukum-dan-kriminal...
4,Fakta Viral Pria Tergeletak dengan Waj...,"Kamis, 30 Mar 2023 14:04 WIB",Rifat Alhamidi - detikJabar,detikJabar,Bandung,Bandung - Polisi memastikan video viral yang m...,https://www.detik.com/jabar/hukum-dan-kriminal...
...,...,...,...,...,...,...,...
3674,Fakta-fakta Kecelakaan Adu Banteng Tew...,"Jumat, 01 Apr 2022 19:54 WIB",Tim detikJateng - detikJateng,detikJateng,Solo,Solo - Kecelakaan maut antara truk dengan mobi...,https://www.detik.com/jateng/berita/d-6012255/...
3675,Jasa Raharja Pati Cairkan Santunan 3 K...,"Jumat, 01 Apr 2022 19:52 WIB",Angling Adhitya Purbaya - detikJateng,detikJateng,Semarang,Semarang - Kecelakaan adu banteng antara truk ...,https://www.detik.com/jateng/bisnis/d-6012252/...
3676,"Jangan Lelet Apalagi Ngebut di Tol, Se...","Jumat, 01 Apr 2022 18:10 WIB",Tim detikcom - detikOto,detikOto,Jakarta,Jakarta - Batas kecepatan kendaraan di jalan s...,https://oto.detik.com/mobil/d-6012027/jangan-l...
3677,Hyundai Ioniq 5 Tambah Daftar Mobil ya...,"Jumat, 01 Apr 2022 17:33 WIB",Dina Rayanti - detikOto,detikOto,Jakarta,"Jakarta - Produsen asal Korea Selatan, Hyundai...",https://oto.detik.com/mobil/d-6011922/hyundai-...
3678,Detik-detik Kecelakaan Adu Banteng yan...,"Jumat, 01 Apr 2022 15:19 WIB",Tim detikcom - detikNews,detikNews,Pemalang,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...,https://news.detik.com/berita/d-6011711/detik-...

Cek Nilai kosong

In [ ]:
if df.isna().any().any():
    print('Ada nilai yang kosong')
else:
    print('Tidak ada nilai yang kosong')

Tidak ada nilai yang kosong

Membersihkan kolom judul

In [ ]:
df_judul = df['Judul']
df_judul

0               Jabar Hari Ini: Sakit Hati Dua Pemain ...
1               Waka DPRD Tanjabbar Tinggalkan TKP Usa...
2               Jalan Raya Casablanca Jakarta Macet di...
3               Pemotor Mabuk Tabrak 3 Anggota Satpol ...
4               Fakta Viral Pria Tergeletak dengan Waj...
                              ...
3674            Fakta-fakta Kecelakaan Adu Banteng Tew...
3675            Jasa Raharja Pati Cairkan Santunan 3 K...
3676            Jangan Lelet Apalagi Ngebut di Tol, Se...
3677            Hyundai Ioniq 5 Tambah Daftar Mobil ya...
3678            Detik-detik Kecelakaan Adu Banteng yan...
Name: Judul, Length: 3679, dtype: object

In [ ]:
df_judul = df_judul.str.strip()
df_judul

0       Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib
1       Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...
2       Jalan Raya Casablanca Jakarta Macet di Kedua Arah
3       Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...
4       Fakta Viral Pria Tergeletak dengan Wajah Tersa...
                              ...
3674    Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...
3675    Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...
3676    Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...
3677    Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...
3678    Detik-detik Kecelakaan Adu Banteng yang Tewask...
Name: Judul, Length: 3679, dtype: object

Membersihkan kolom penulis

In [ ]:
df_penulis = df['Penulis']
df_penulis

0                 Tim detikJabar - detikJabar
1                Ferdi Almunanda - detikSumut
2                 Jabbar Ramdhani - detikNews
3                   Deny Prastyo - detikJatim
4                 Rifat Alhamidi - detikJabar
                        ...
3674            Tim detikJateng - detikJateng
3675    Angling Adhitya Purbaya - detikJateng
3676                  Tim detikcom - detikOto
3677                  Dina Rayanti - detikOto
3678                 Tim detikcom - detikNews
Name: Penulis, Length: 3679, dtype: object

In [ ]:
def remove_after_dash(nama_penulis):
    return nama_penulis.split('-')[0].strip()

df_penulis = df_penulis.apply(remove_after_dash)
df_penulis

0                Tim detikJabar
1               Ferdi Almunanda
2               Jabbar Ramdhani
3                  Deny Prastyo
4                Rifat Alhamidi
                 ...
3674            Tim detikJateng
3675    Angling Adhitya Purbaya
3676               Tim detikcom
3677               Dina Rayanti
3678               Tim detikcom
Name: Penulis, Length: 3679, dtype: object

Membersihkan Kolom deskripsi

In [ ]:
df_desc = df['Deskripsi']
df_desc

0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: Deskripsi, Length: 3679, dtype: object

In [ ]:
# df_desc = df_desc.str.split('-').str.get(1)
# df_desc

# gk jadi, malah jadi banyak missing

## **Data Tranformating**

---

url menjadi id

In [ ]:
df_id = df['Url']
df_id

0       https://www.detik.com/jabar/berita/d-6646815/j...
1       https://www.detik.com/sumut/berita/d-6647430/w...
2       https://news.detik.com/berita/d-6647094/jalan-...
3       https://www.detik.com/jatim/hukum-dan-kriminal...
4       https://www.detik.com/jabar/hukum-dan-kriminal...
                              ...
3674    https://www.detik.com/jateng/berita/d-6012255/...
3675    https://www.detik.com/jateng/bisnis/d-6012252/...
3676    https://oto.detik.com/mobil/d-6012027/jangan-l...
3677    https://oto.detik.com/mobil/d-6011922/hyundai-...
3678    https://news.detik.com/berita/d-6011711/detik-...
Name: Url, Length: 3679, dtype: object

In [ ]:
df_id = df_id.str.split('//').str.get(1)
df_id

0       www.detik.com/jabar/berita/d-6646815/jabar-har...
1       www.detik.com/sumut/berita/d-6647430/waka-dprd...
2       news.detik.com/berita/d-6647094/jalan-raya-cas...
3       www.detik.com/jatim/hukum-dan-kriminal/d-66470...
4       www.detik.com/jabar/hukum-dan-kriminal/d-66464...
                              ...
3674    www.detik.com/jateng/berita/d-6012255/fakta-fa...
3675    www.detik.com/jateng/bisnis/d-6012252/jasa-rah...
3676    oto.detik.com/mobil/d-6012027/jangan-lelet-apa...
3677    oto.detik.com/mobil/d-6011922/hyundai-ioniq-5-...
3678    news.detik.com/berita/d-6011711/detik-detik-ke...
Name: Url, Length: 3679, dtype: object

In [ ]:
import re
pattern = r'd-6\d+'

id = []
for url in df_id:
    match = re.search(pattern, url)
    if match:
        id.append([match.group()])

columns = ['id']
df_id = pd.DataFrame(id, columns=columns)
print(df_id)

             id
0     d-6646815
1     d-6647430
2     d-6647094
3     d-6647008
4     d-6646405
...         ...
3674  d-6012255
3675  d-6012252
3676  d-6012027
3677  d-6011922
3678  d-6011711

[3679 rows x 1 columns]

Memecah tanggal menjadi 3 kolom baru, yaitu hari, tanggal, waktu
dan mentransformasikan format nya biar sama

In [ ]:
if df['Tanggal'].str.contains('WIB').all():
    print("Semua baris mengandung kata WIB")
else:
    print("Tidak semua baris mengandung kata WIB")

Semua baris mengandung kata WIB

In [ ]:
df_tanggal = df['Tanggal']
df_tanggal

0       Kamis, 30 Mar 2023 22:00 WIB
1       Kamis, 30 Mar 2023 21:44 WIB
2       Kamis, 30 Mar 2023 18:49 WIB
3       Kamis, 30 Mar 2023 17:59 WIB
4       Kamis, 30 Mar 2023 14:04 WIB
                    ...
3674    Jumat, 01 Apr 2022 19:54 WIB
3675    Jumat, 01 Apr 2022 19:52 WIB
3676    Jumat, 01 Apr 2022 18:10 WIB
3677    Jumat, 01 Apr 2022 17:33 WIB
3678    Jumat, 01 Apr 2022 15:19 WIB
Name: Tanggal, Length: 3679, dtype: object

In [ ]:
df_tanggal = df_tanggal.str.replace(' WIB', '')
df_tanggal

0       Kamis, 30 Mar 2023 22:00
1       Kamis, 30 Mar 2023 21:44
2       Kamis, 30 Mar 2023 18:49
3       Kamis, 30 Mar 2023 17:59
4       Kamis, 30 Mar 2023 14:04
                  ...
3674    Jumat, 01 Apr 2022 19:54
3675    Jumat, 01 Apr 2022 19:52
3676    Jumat, 01 Apr 2022 18:10
3677    Jumat, 01 Apr 2022 17:33
3678    Jumat, 01 Apr 2022 15:19
Name: Tanggal, Length: 3679, dtype: object

In [ ]:
df_hari = df_tanggal.str.split(',').str.get(0)
df_hari

0       Kamis
1       Kamis
2       Kamis
3       Kamis
4       Kamis
        ...
3674    Jumat
3675    Jumat
3676    Jumat
3677    Jumat
3678    Jumat
Name: Tanggal, Length: 3679, dtype: object

In [ ]:
df_jam = df_tanggal.str.split(' ').str.get(-1)
df_jam

0       22:00
1       21:44
2       18:49
3       17:59
4       14:04
        ...
3674    19:54
3675    19:52
3676    18:10
3677    17:33
3678    15:19
Name: Tanggal, Length: 3679, dtype: object

In [ ]:
tanggal = df_tanggal.str.split(' ', expand=True)
df_tanggal_new = tanggal[[1, 2, 3]]
print(df_tanggal_new)

       1    2     3
0     30  Mar  2023
1     30  Mar  2023
2     30  Mar  2023
3     30  Mar  2023
4     30  Mar  2023
...   ..  ...   ...
3674  01  Apr  2022
3675  01  Apr  2022
3676  01  Apr  2022
3677  01  Apr  2022
3678  01  Apr  2022

[3679 rows x 3 columns]

In [ ]:
df_tanggal_new[2].value_counts()

Mei    385
Jan    367
Jul    365
Feb    321
Apr    319
Jun    315
Sep    291
Okt    289
Agu    274
Nov    272
Des    256
Mar    225
Name: 2, dtype: int64

In [ ]:
bulan = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des']
angka = [1, 2, 3, 4, 5, 6, 7 ,8, 9, 10, 11, 12]

df_tanggal_new[2] = df_tanggal_new[2].replace (bulan, angka)
print(df_tanggal_new)

       1  2     3
0     30  3  2023
1     30  3  2023
2     30  3  2023
3     30  3  2023
4     30  3  2023
...   .. ..   ...
3674  01  4  2022
3675  01  4  2022
3676  01  4  2022
3677  01  4  2022
3678  01  4  2022

[3679 rows x 3 columns]

In [ ]:
df_tanggal_new = df_tanggal_new.astype(str)
print(df_tanggal_new)

       1  2     3
0     30  3  2023
1     30  3  2023
2     30  3  2023
3     30  3  2023
4     30  3  2023
...   .. ..   ...
3674  01  4  2022
3675  01  4  2022
3676  01  4  2022
3677  01  4  2022
3678  01  4  2022

[3679 rows x 3 columns]

In [ ]:
df_tanggal_new = df_tanggal_new.apply(lambda x: "/".join(x), axis=1)
print(df_tanggal_new)

0       30/3/2023
1       30/3/2023
2       30/3/2023
3       30/3/2023
4       30/3/2023
          ...
3674    01/4/2022
3675    01/4/2022
3676    01/4/2022
3677    01/4/2022
3678    01/4/2022
Length: 3679, dtype: object

## **Menggabungkan kembali berbagai kolom yang sudah dibersihkan dan membuat csv baru**

In [ ]:
df_tanggal_number = df_tanggal_new[1]
df_bulan = df_tanggal_new[2]
df_tahun = df_tanggal_new[3]
df_kota = df['Kota']
df_label = df['Label']

df_clean_phase1 = pd.concat([df_id, df_hari, df_tanggal_number, df_bulan, df_tahun, df_judul, df_kota, df_label, df_penulis, df_desc], axis=1)
df_clean_phase1

,id,Tanggal,1,2,3,Judul,Kota,Label,Penulis,Deskripsi
0,d-6646815,Kamis,30,3,2023,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,d-6647430,Kamis,30,3,2023,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,d-6647094,Kamis,30,3,2023,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,d-6647008,Kamis,30,3,2023,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,d-6646405,Kamis,30,3,2023,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...
3674,d-6012255,Jumat,01,4,2022,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,d-6012252,Jumat,01,4,2022,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,d-6012027,Jumat,01,4,2022,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,d-6011922,Jumat,01,4,2022,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,d-6011711,Jumat,01,4,2022,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
df_clean_phase1 = df_clean_phase1.rename(columns={"Tanggal":"hari", 1:"tanggal",2 :"bulan", 3 :"tahun", "Judul":"judul", "Kota":"kota", "Label":"label", "Penulis":"penulis","Deskripsi":"deskripsi"})
df_clean_phase1

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,d-6646815,Kamis,30,3,2023,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,d-6647430,Kamis,30,3,2023,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,d-6647094,Kamis,30,3,2023,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,d-6647008,Kamis,30,3,2023,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,d-6646405,Kamis,30,3,2023,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...
3674,d-6012255,Jumat,01,4,2022,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,d-6012252,Jumat,01,4,2022,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,d-6012027,Jumat,01,4,2022,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,d-6011922,Jumat,01,4,2022,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,d-6011711,Jumat,01,4,2022,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
if df_clean_phase1['id'].str.contains('d-').all():
    print("Semua baris mengandung kata d")
else:
    print("Tidak semua baris mengandung kata d")

Semua baris mengandung kata d

In [ ]:
df_clean_phase1['id'] = df_clean_phase1['id'].str.replace('d-', '')

df_clean_phase1['id'] = pd.to_numeric(df_clean_phase1['id'])
df_clean_phase1['tanggal'] = pd.to_numeric(df_clean_phase1['tanggal'])

df_clean_phase1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3679 entries, 0 to 3678
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         3679 non-null   int64
 1   hari       3679 non-null   object
 2   tanggal    3679 non-null   int64
 3   bulan      3679 non-null   int64
 4   tahun      3679 non-null   object
 5   judul      3679 non-null   object
 6   kota       3679 non-null   object
 7   label      3679 non-null   object
 8   penulis    3679 non-null   object
 9   deskripsi  3679 non-null   object
dtypes: int64(3), object(7)
memory usage: 287.5+ KB

In [ ]:
df_clean_phase1.to_csv('fix_detik.com_clean_phase1.csv')
df_clean_phase1

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,6646815,Kamis,30,3,2023,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,6647430,Kamis,30,3,2023,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,6647094,Kamis,30,3,2023,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,6647008,Kamis,30,3,2023,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,6646405,Kamis,30,3,2023,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,6012252,Jumat,1,4,2022,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,6012027,Jumat,1,4,2022,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,6011922,Jumat,1,4,2022,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,6011711,Jumat,1,4,2022,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
from google.colab import files
files.download('fix_detik.com_clean_phase1.csv')

## ***Phase 3***

---

Mungkin Preprocessing Deskripsi : Case Folding, Stemming & Lemmatization, Stop-word, Tokenization

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving fix_detik.com_clean_phase1_full_version.csv to fix_detik.com_clean_phase1_full_version.csv

In [ ]:
df3 = pd.read_csv('fix_detik.com_clean_phase1_full_version.csv')
df3

,Unnamed: 0,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...,...
3674,3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
df3 = df3.drop(columns='Unnamed: 0')
df3

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
df3.label.value_counts()

detikNews       1304
detikJabar       466
detikJatim       458
detikJateng      355
detikOto         350
detikBali        264
detikSumut       190
detikSulsel      181
detikFinance      47
detikEdu          20
detikHealth       16
detikHot          13
detikInet         10
Sport              4
Sepakbola          1
Name: label, dtype: int64

### **Basic Data Cleaning (deskripsi)**

In [ ]:
df_desc = df3['deskripsi']
df_desc

0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
panjang_kata = df_desc.apply(len)
panjang_kata

0       14183
1        2206
2        1335
3        2837
4        2666
        ...
3674     4723
3675     2726
3676     2810
3677     2858
3678     1766
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
import re # re ini regular expression yang tadi di atas di jelasin
def remove_html(text): #define variable fungsi remove html/html tag dalam bentuk dari variable apapun yang berbentuk text
    text = text.replace("\n"," ") #yang ini tiap ada baris baru pake /n di ganti pake spasi aja yang ada di var text
    pattern = re.compile('<.*?>') #semua HTML tags
    return pattern.sub(r'', text) #return

In [ ]:
df_desc_processed = df_desc.apply(remove_html)
print(df_desc_processed)

0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
def remove_headings(text):
    pattern = re.compile('\w+:')
    return pattern.sub(r'', text)

In [ ]:
df_desc_processed = df_desc.apply(remove_headings)
print (df_desc_processed)
# liat EXAM : <~ ini adalah heading yang hilang dari contoh sebelumnya

0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
def replace_mult_spaces(text):
    text = text.replace("&quot","")
    pattern = re.compile(' +')
    text = pattern.sub(r' ', text)
    text = text.strip()
    return text

def replace_other_chars(text):
    pattern = re.compile(r'[()!@&;#]')
    text = pattern.sub(r'', text)
    return text

In [ ]:
df_desc_processed = df_desc.apply(replace_mult_spaces)
df_desc_processed = df_desc.apply(replace_other_chars)
print (df_desc_processed)

0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa 17 tewas usai...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
def clean_text(text):
    text = remove_html(text)
    text = remove_headings(text)
    text = replace_mult_spaces(text)
    text = replace_other_chars(text)
    text = text.lower()
    return text

In [ ]:
df_desc_processed_clean = df_desc.apply(clean_text)
print(df_desc_processed_clean)

0       bandung - beragam peristiwa terjadi di jawa ba...
1       jambi - abg bernama siti nuanisa 17 tewas usai...
2       jakarta - kemacetan terjadi di jalan raya casa...
3       surabaya - polisi telah menetapkan pemotor ber...
4       bandung - polisi memastikan video viral yang m...
                              ...
3674    solo - kecelakaan maut antara truk dengan mobi...
3675    semarang - kecelakaan adu banteng antara truk ...
3676    jakarta - batas kecepatan kendaraan di jalan s...
3677    jakarta - produsen asal korea selatan, hyundai...
3678    pemalang - sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
panjang_kata_new = df_desc_processed_clean.apply(len)
print("Sebelum : ")
print(panjang_kata)
print("Sesudah : ")
print(panjang_kata_new)

Sebelum :
0       14183
1        2206
2        1335
3        2837
4        2666
        ...
3674     4723
3675     2726
3676     2810
3677     2858
3678     1766
Name: deskripsi, Length: 3679, dtype: int64
Sesudah :
0       14095
1        2162
2        1298
3        2791
4        2628
        ...
3674     4654
3675     2679
3676     2767
3677     2795
3678     1718
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
print(df_desc_processed_clean.apply(clean_text))
print('------------------------------------------')
print(df_desc)

0       bandung - beragam peristiwa terjadi di jawa ba...
1       jambi - abg bernama siti nuanisa 17 tewas usai...
2       jakarta - kemacetan terjadi di jalan raya casa...
3       surabaya - polisi telah menetapkan pemotor ber...
4       bandung - polisi memastikan video viral yang m...
                              ...
3674    solo - kecelakaan maut antara truk dengan mobi...
3675    semarang - kecelakaan adu banteng antara truk ...
3676    jakarta - batas kecepatan kendaraan di jalan s...
3677    jakarta - produsen asal korea selatan, hyundai...
3678    pemalang - sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object
------------------------------------------
0       Bandung - Beragam peristiwa terjadi di Jawa Ba...
1       Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2       Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3       Surabaya - Polisi telah menetapkan pemotor ber...
4       Bandung - Polisi memastikan video viral yang m...
                              ...
3674    Solo - Kecelakaan maut antara truk dengan mobi...
3675    Semarang - Kecelakaan adu banteng antara truk ...
3676    Jakarta - Batas kecepatan kendaraan di jalan s...
3677    Jakarta - Produsen asal Korea Selatan, Hyundai...
3678    Pemalang - Sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

### **Stemming dengan Sastrawi**

In [ ]:
df_stemming = df_desc_processed_clean
print(df_stemming)

0       bandung - beragam peristiwa terjadi di jawa ba...
1       jambi - abg bernama siti nuanisa 17 tewas usai...
2       jakarta - kemacetan terjadi di jalan raya casa...
3       surabaya - polisi telah menetapkan pemotor ber...
4       bandung - polisi memastikan video viral yang m...
                              ...
3674    solo - kecelakaan maut antara truk dengan mobi...
3675    semarang - kecelakaan adu banteng antara truk ...
3676    jakarta - batas kecepatan kendaraan di jalan s...
3677    jakarta - produsen asal korea selatan, hyundai...
3678    pemalang - sebanyak 5 orang tewas dan 4 luka a...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
!pip install nltk
!pip install Sastrawi

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 9.9 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

df_stemming_next = df_stemming.apply(stemmer.stem)
print(df_stemming_next)

0       bandung - agam peristiwa jadi di jawa barat ja...
1       jambi - abg nama siti nuanisa 17 tewas usai mo...
2       jakarta - macet jadi di jalan raya casablanca ...
3       surabaya - polisi telah tetap motor inisial ra...
4       bandung - polisi pasti video viral yang lihat ...
                              ...
3674    solo - celaka maut antara truk dengan mobil el...
3675    semarang - celaka adu banteng antara truk deng...
3676    jakarta - batas cepat kendara di jalan sudah a...
3677    jakarta - produsen asal korea selatan hyundai ...
3678    malang - banyak 5 orang tewas dan 4 luka akiba...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
x = df_stemming.apply(len)
y = df_stemming_next.apply(len)
print("Sebelum : ")
print(x)
print("Sesudah : ")
print(y)

Sebelum :
0       14095
1        2162
2        1298
3        2791
4        2628
        ...
3674     4654
3675     2679
3676     2767
3677     2795
3678     1718
Name: deskripsi, Length: 3679, dtype: int64
Sesudah :
0       12159
1        1928
2        1128
3        2368
4        2232
        ...
3674     4094
3675     2307
3676     2361
3677     2527
3678     1486
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
df_stemming_next = df_stemming_next.to_csv('fix_clean_data_stemmed.csv', index=False)
df_stemming_next

In [ ]:
from google.colab import files
files.download('fix_clean_data_stemmed.csv')

### Tokenization

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving fix_clean_data_stemmed.csv to fix_clean_data_stemmed (1).csv

In [ ]:
df_stemming_next = pd.read_csv('fix_clean_data_stemmed.csv')
df_stemming_next

                                              deskripsi
0     bandung - agam peristiwa jadi di jawa barat ja...
1     jambi - abg nama siti nuanisa 17 tewas usai mo...
2     jakarta - macet jadi di jalan raya casablanca ...
3     surabaya - polisi telah tetap motor inisial ra...
4     bandung - polisi pasti video viral yang lihat ...
...                                                 ...
3674  solo - celaka maut antara truk dengan mobil el...
3675  semarang - celaka adu banteng antara truk deng...
3676  jakarta - batas cepat kendara di jalan sudah a...
3677  jakarta - produsen asal korea selatan hyundai ...
3678  malang - banyak 5 orang tewas dan 4 luka akiba...

[3679 rows x 1 columns]

In [ ]:
kata_after_stemmed = df_stemming_next['deskripsi'].apply(lambda x: len(x))
kata_after_stemmed

0       12159
1        1928
2        1128
3        2368
4        2232
        ...
3674     4094
3675     2307
3676     2361
3677     2527
3678     1486
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
import nltk
nltk.download('punkt')
import pandas as pd

from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [ ]:
df_tokens = df_stemming_next['deskripsi'].apply(word_tokenize)

print(df_tokens)

0       [bandung, -, agam, peristiwa, jadi, di, jawa, ...
1       [jambi, -, abg, nama, siti, nuanisa, 17, tewas...
2       [jakarta, -, macet, jadi, di, jalan, raya, cas...
3       [surabaya, -, polisi, telah, tetap, motor, ini...
4       [bandung, -, polisi, pasti, video, viral, yang...
                              ...
3674    [solo, -, celaka, maut, antara, truk, dengan, ...
3675    [semarang, -, celaka, adu, banteng, antara, tr...
3676    [jakarta, -, batas, cepat, kendara, di, jalan,...
3677    [jakarta, -, produsen, asal, korea, selatan, h...
3678    [malang, -, banyak, 5, orang, tewas, dan, 4, l...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
df_tokens.to_csv('df_stemmed_tokens.csv', index=False)
files.download('df_stemmed_tokens.csv')

In [ ]:
df_tokens_2 = pd.read_csv('df_stemmed_tokens.csv')
df_tokens_2

                                              deskripsi
0     ['bandung', '-', 'agam', 'peristiwa', 'jadi', ...
1     ['jambi', '-', 'abg', 'nama', 'siti', 'nuanisa...
2     ['jakarta', '-', 'macet', 'jadi', 'di', 'jalan...
3     ['surabaya', '-', 'polisi', 'telah', 'tetap', ...
4     ['bandung', '-', 'polisi', 'pasti', 'video', '...
...                                                 ...
3674  ['solo', '-', 'celaka', 'maut', 'antara', 'tru...
3675  ['semarang', '-', 'celaka', 'adu', 'banteng', ...
3676  ['jakarta', '-', 'batas', 'cepat', 'kendara', ...
3677  ['jakarta', '-', 'produsen', 'asal', 'korea', ...
3678  ['malang', '-', 'banyak', '5', 'orang', 'tewas...

[3679 rows x 1 columns]

In [ ]:
after_tokens = df_tokens_2['deskripsi'].apply(lambda x: len(x))
after_tokens

0       18118
1        2886
2        1696
3        3578
4        3313
        ...
3674     6129
3675     3487
3676     3574
3677     3722
3678     2252
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
df_phase3_complete_tokens_ver = pd.concat([df3['id'], df3['hari'], df3['tanggal'], df3['bulan'], df3['tahun'], df3['judul'], df3['kota'], df3['label'], df3['penulis'], df_tokens_2], axis=1)
df_phase3_complete_tokens_ver

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"['bandung', '-', 'agam', 'peristiwa', 'jadi', ..."
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"['jambi', '-', 'abg', 'nama', 'siti', 'nuanisa..."
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,"['jakarta', '-', 'macet', 'jadi', 'di', 'jalan..."
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"['surabaya', '-', 'polisi', 'telah', 'tetap', ..."
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"['bandung', '-', 'polisi', 'pasti', 'video', '..."
...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"['solo', '-', 'celaka', 'maut', 'antara', 'tru..."
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"['semarang', '-', 'celaka', 'adu', 'banteng', ..."
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"['jakarta', '-', 'batas', 'cepat', 'kendara', ..."
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"['jakarta', '-', 'produsen', 'asal', 'korea', ..."
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"['malang', '-', 'banyak', '5', 'orang', 'tewas..."

In [ ]:
df_phase3_complete_tokens_ver.to_csv('df_phase3_complete_tokens_ver.csv', index=False)
files.download('df_phase3_complete_tokens_ver.csv')

### Stopwords

In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

# Mengambil daftar stopwords bahasa Indonesia dari NLTK
stop_words = set(stopwords.words('indonesian'))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
df_stopwords = df_tokens_2['deskripsi'].apply(lambda x: x.split())

# Menghapus stopwords dari teks pada dataframe
df_clean_stopwords = df_stopwords.apply(lambda x: [token for token in x if token.lower() not in stop_words])

df_clean_stopwords

0       [['bandung',, '-',, 'agam',, 'peristiwa',, 'ja...
1       [['jambi',, '-',, 'abg',, 'nama',, 'siti',, 'n...
2       [['jakarta',, '-',, 'macet',, 'jadi',, 'di',, ...
3       [['surabaya',, '-',, 'polisi',, 'telah',, 'tet...
4       [['bandung',, '-',, 'polisi',, 'pasti',, 'vide...
                              ...
3674    [['solo',, '-',, 'celaka',, 'maut',, 'antara',...
3675    [['semarang',, '-',, 'celaka',, 'adu',, 'bante...
3676    [['jakarta',, '-',, 'batas',, 'cepat',, 'kenda...
3677    [['jakarta',, '-',, 'produsen',, 'asal',, 'kor...
3678    [['malang',, '-',, 'banyak',, '5',, 'orang',, ...
Name: deskripsi, Length: 3679, dtype: object

In [ ]:
word_after_stopwords = df_clean_stopwords.apply(lambda x: len(x))
word_after_stopwords

0       1986
1        319
2        189
3        403
4        360
        ...
3674     678
3675     393
3676     404
3677     398
3678     255
Name: deskripsi, Length: 3679, dtype: int64

In [ ]:
df3

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,Bandung - Beragam peristiwa terjadi di Jawa Ba...
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,Jambi - ABG bernama Siti Nuanisa (17) tewas us...
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,Jakarta - Kemacetan terjadi di Jalan Raya Casa...
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,Surabaya - Polisi telah menetapkan pemotor ber...
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,Bandung - Polisi memastikan video viral yang m...
...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,Solo - Kecelakaan maut antara truk dengan mobi...
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,Semarang - Kecelakaan adu banteng antara truk ...
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,Jakarta - Batas kecepatan kendaraan di jalan s...
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"Jakarta - Produsen asal Korea Selatan, Hyundai..."
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,Pemalang - Sebanyak 5 orang tewas dan 4 luka a...

In [ ]:
df_phase3_complete = pd.concat([df3['id'], df3['hari'], df3['tanggal'], df3['bulan'], df3['tahun'], df3['judul'], df3['kota'], df3['label'], df3['penulis'], df_clean_stopwords], axis=1)
df_phase3_complete

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[['bandung',, '-',, 'agam',, 'peristiwa',, 'ja..."
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[['jambi',, '-',, 'abg',, 'nama',, 'siti',, 'n..."
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,"[['jakarta',, '-',, 'macet',, 'jadi',, 'di',, ..."
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[['surabaya',, '-',, 'polisi',, 'telah',, 'tet..."
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[['bandung',, '-',, 'polisi',, 'pasti',, 'vide..."
...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[['solo',, '-',, 'celaka',, 'maut',, 'antara',..."
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[['semarang',, '-',, 'celaka',, 'adu',, 'bante..."
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[['jakarta',, '-',, 'batas',, 'cepat',, 'kenda..."
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[['jakarta',, '-',, 'produsen',, 'asal',, 'kor..."
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[['malang',, '-',, 'banyak',, '5',, 'orang',, ..."

In [ ]:
df_phase3_complete.to_csv('df_phase3_complete.csv', index=False)
files.download('df_phase3_complete.csv')

In [ ]:
df_phase3_complete['deskripsi'][1]

# **Kita Coba Menentukan jenis kendaraan**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving df_phase3_complete.csv to df_phase3_complete.csv

In [ ]:
df4 = pd.read_csv('df_phase3_complete.csv')
df4

In [ ]:
import pandas as pd
import re

vehicle_keywords = ['mobil', 'motor', 'truk', 'pesawat', 'kapal', 'bus', 'kereta', 'perahu']

# 3. Definisikan fungsi untuk mencari kendaraan pada deskripsi
def find_vehicles(description):
    vehicles = []
    for keyword in vehicle_keywords:
        if re.search(keyword, description, re.IGNORECASE):
            vehicles.append(keyword)
    return vehicles

In [ ]:
# contoh data
df4 = pd.read_csv('df_phase3_complete.csv')

# 4. Terapkan fungsi pada kolom deskripsi dan tambahkan kolom baru yang berisi list kendaraan
df4['deteksi_kendaraan'] = df4['deskripsi'].apply(find_vehicles)

# 5. Tampilkan DataFrame yang telah diupdate
print(df4)

           id   hari  tanggal  bulan   tahun  \
0     6646815  Kamis       30      3  2023.0
1     6647430  Kamis       30      3  2023.0
2     6647094  Kamis       30      3  2023.0
3     6647008  Kamis       30      3  2023.0
4     6646405  Kamis       30      3  2023.0
...       ...    ...      ...    ...     ...
3674  6012255  Jumat        1      4  2022.0
3675  6012252  Jumat        1      4  2022.0
3676  6012027  Jumat        1      4  2022.0
3677  6011922  Jumat        1      4  2022.0
3678  6011711  Jumat        1      4  2022.0

                                                  judul      kota  \
0     Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib   Bandung
1     Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...     Jambi
2     Jalan Raya Casablanca Jakarta Macet di Kedua Arah   Jakarta
3     Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...  Surabaya
4     Fakta Viral Pria Tergeletak dengan Wajah Tersa...   Bandung
...                                                 ...       ...
3674  Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...      Solo
3675  Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...  Semarang
3676  Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...   Jakarta
3677  Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...   Jakarta
3678  Detik-detik Kecelakaan Adu Banteng yang Tewask...  Pemalang

            label                  penulis  \
0      detikJabar           Tim detikJabar
1      detikSumut          Ferdi Almunanda
2       detikNews          Jabbar Ramdhani
3      detikJatim             Deny Prastyo
4      detikJabar           Rifat Alhamidi
...           ...                      ...
3674  detikJateng          Tim detikJateng
3675  detikJateng  Angling Adhitya Purbaya
3676     detikOto             Tim detikcom
3677     detikOto             Dina Rayanti
3678    detikNews             Tim detikcom

                                              deskripsi     deteksi_kendaraan
0     ["['bandung',", "'-',", "'agam',", "'peristiwa...  [mobil, motor, truk]
1     ["['jambi',", "'-',", "'abg',", "'nama',", "'s...        [mobil, motor]
2     ["['jakarta',", "'-',", "'macet',", "'jadi',",...                    []
3     ["['surabaya',", "'-',", "'polisi',", "'telah'...               [motor]
4     ["['bandung',", "'-',", "'polisi',", "'pasti',...               [motor]
...                                                 ...                   ...
3674  ["['solo',", "'-',", "'celaka',", "'maut',", "...    [mobil, truk, bus]
3675  ["['semarang',", "'-',", "'celaka',", "'adu',"...    [mobil, truk, bus]
3676  ["['jakarta',", "'-',", "'batas',", "'cepat',"...         [mobil, truk]
3677  ["['jakarta',", "'-',", "'produsen',", "'asal'...        [mobil, motor]
3678  ["['malang',", "'-',", "'banyak',", "'5',", "'...    [mobil, truk, bus]

[3679 rows x 11 columns]

In [ ]:
df4

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","[mobil, motor, truk]"
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","[mobil, motor]"
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,"[""['jakarta',"", ""'-',"", ""'macet',"", ""'jadi',"",...",[]
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",[motor]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",[motor]
...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","[mobil, truk, bus]"
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","[mobil, truk, bus]"
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","[mobil, truk]"
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","[mobil, motor]"
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","[mobil, truk, bus]"

In [ ]:
df4.to_csv('after_stopwords_jenis_kendaraan_kasar.csv', index=False)
files.download('after_stopwords_jenis_kendaraan_kasar.csv')

# Model kendaraan, kondisi korban

In [ ]:
df5 = pd.read_csv('after_stopwords_jenis_kendaraan_kasar.csv')

In [ ]:
vehicle_models = ['minibus', 'truk biasa', 'kontainer', 'sedan', 'pikap', 'mikrolet', 'taksi', 'jeep', 'metromini', 'tronton', 'truk gandeng', 'kopaja', 'angkot']

# 3. Definisikan fungsi untuk mencari kendaraan pada deskripsi
def models_vehicles(description):
    models = []
    for keyword in vehicle_models:
        if re.search(keyword, description, re.IGNORECASE):
            models.append(keyword)
    return models

In [ ]:
df5['model_kendaraan'] = df5['deskripsi'].apply(models_vehicles)

In [ ]:
df5

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","['mobil', 'motor', 'truk']",[sedan]
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","['mobil', 'motor']",[sedan]
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,"[""['jakarta',"", ""'-',"", ""'macet',"", ""'jadi',"",...",[],[]
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",['motor'],[sedan]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",['motor'],[sedan]
...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","['mobil', 'truk', 'bus']",[minibus]
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","['mobil', 'truk', 'bus']",[sedan]
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","['mobil', 'truk']",[sedan]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","['mobil', 'motor']",[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","['mobil', 'truk', 'bus']",[]

kondisi

In [ ]:
condition = condition = ['tewas', 'kritis', 'luka parah', 'terluka', 'cedera', 'selamat', 'meninggal']

# 3. Definisikan fungsi untuk mencari kendaraan pada deskripsi
def condition_detect(description):
    condi = []
    for keyword in condition:
        if re.search(keyword, description, re.IGNORECASE):
            condi.append(keyword)
    return condi

In [ ]:
df5['kondisi'] = df5['deskripsi'].apply(condition_detect)

In [ ]:
df5

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","['mobil', 'motor', 'truk']",[sedan],[tewas]
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","['mobil', 'motor']",[sedan],[tewas]
2,6647094,Kamis,30,3,2023.0,Jalan Raya Casablanca Jakarta Macet di Kedua Arah,Jakarta,detikNews,Jabbar Ramdhani,"[""['jakarta',"", ""'-',"", ""'macet',"", ""'jadi',"",...",[],[],[]
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",['motor'],[sedan],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",['motor'],[sedan],[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","['mobil', 'truk', 'bus']",[minibus],[tewas]
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","['mobil', 'truk', 'bus']",[sedan],[tewas]
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","['mobil', 'truk']",[sedan],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","['mobil', 'motor']",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","['mobil', 'truk', 'bus']",[],[tewas]

In [ ]:
print(df5['deteksi_kendaraan'].value_counts())

['mobil', 'motor']                               426
['mobil', 'truk']                                364
[]                                               328
['mobil']                                        314
['motor']                                        313
                                                ...
['mobil', 'truk', 'perahu']                        1
['mobil', 'motor', 'pesawat', 'bus']               1
['motor', 'truk', 'perahu']                        1
['pesawat', 'kereta']                              1
['mobil', 'motor', 'bus', 'kereta', 'perahu']      1
Name: deteksi_kendaraan, Length: 79, dtype: int64

In [ ]:
df_detik = df5.loc[df5['label'] == 'detikNews']
print(df_detik)

           id   hari  tanggal  bulan   tahun  \
2     6647094  Kamis       30      3  2023.0
9     6645626  Kamis       30      3  2023.0
10    6645441   Rabu       29      3  2023.0
11    6644826   Rabu       29      3  2023.0
21    6639576  Senin       27      3  2023.0
...       ...    ...      ...    ...     ...
3652  6016540  Senin        4      4  2022.0
3655  6016172  Senin        4      4  2022.0
3661  6015124  Senin        4      4  2022.0
3671  6012996  Sabtu        2      4  2022.0
3678  6011711  Jumat        1      4  2022.0

                                                  judul      kota      label  \
2     Jalan Raya Casablanca Jakarta Macet di Kedua Arah   Jakarta  detikNews
9     Sejumlah Titik di Tol JORR Arah Jakarta Macet ...   Jakarta  detikNews
10    Ngeri Kecelakaan Angkot Vs Truk di Bogor, Sopi...     Bogor  detikNews
11    Pelajar SMA Tewas Ditabrak Mercy di Jaksel, Be...   Jakarta  detikNews
21    Separator Pecah Berhamburan di Jalan, Flyover ...   Jakarta  detikNews
...                                                 ...       ...        ...
3652  Evaluasi ETLE di Tol, Kakorlantas: Ubah Budaya...   Jakarta  detikNews
3655  Truk Terbalik di Km 18 Tol Ancol Akibat Pecah Ban   Jakarta  detikNews
3661  Diduga Korban Tabrak Lari, Pengendara Motor Te...   Jakarta  detikNews
3671  Wali Kota Bogor Larang Sahur on The Road: Sila...     Bogor  detikNews
3678  Detik-detik Kecelakaan Adu Banteng yang Tewask...  Pemalang  detikNews

                                 penulis  \
2                        Jabbar Ramdhani
9                      Yulida Medistiara
10                             M Solihin
11    Wildan Noviansah, Devi Puspitasari
21                          Mei Amelia R
...                                  ...
3652                       Atta Kharisma
3655                        Isal Mawardi
3661                 Wilda Hayatun Nufus
3671                              Antara
3678                        Tim detikcom

                                              deskripsi  \
2     ["['jakarta',", "'-',", "'macet',", "'jadi',",...
9     ["['jakarta',", "'-',", "'lalu',", "'lintas',"...
10    ["['bogor',", "'-',", "'celaka',", "'libat',",...
11    ["['jakarta',", "'-',", "'orang',", "'ajar',",...
21    ["['jakarta',", "'-',", "'separator',", "'jala...
...                                                 ...
3652  ["['jakarta',", "'-',", "'kakorlantas',", "'po...
3655  ["['jakarta',", "'-',", "'celaka',", "'lalu',"...
3661  ["['jakarta',", "'-',", "'orang',", "'kendara'...
3671  ["['bogor',", "'-',", "'wali',", "'kota',", "'...
3678  ["['malang',", "'-',", "'banyak',", "'5',", "'...

              deteksi_kendaraan             model_kendaraan    kondisi
2                            []                          []         []
9                            []                     [sedan]         []
10     ['motor', 'truk', 'bus']  [kontainer, sedan, angkot]    [tewas]
11           ['mobil', 'motor']                     [sedan]    [tewas]
21              ['truk', 'bus']                          []         []
...                         ...                         ...        ...
3652                         []                          []  [selamat]
3655                   ['truk']                          []    [tewas]
3661  ['mobil', 'motor', 'bus']                   [minibus]    [tewas]
3671                  ['mobil']                          []         []
3678   ['mobil', 'truk', 'bus']                          []    [tewas]

[1304 rows x 13 columns]

In [ ]:
df5.to_csv('after_stopword_until_condition.csv', index=False)
files.download('after_stopword_until_condition.csv')

### Data Cleaning Part 2

---

menghapus baris yang kira kira tidak mengacu pada konteks laka lantas

In [ ]:
uploaded = files.upload()

Saving after_stopword_until_condition.csv to after_stopword_until_condition (1).csv

In [ ]:
df6 = pd.read_csv('after_stopword_until_condition.csv')

Menghapus baris yang kolom deteksi_kendaraan nya kosong

In [ ]:
df6_process = df6['deteksi_kendaraan'].apply(len)
df6_process

0       26
1       18
2        2
3        9
4        9
        ..
3674    24
3675    24
3676    17
3677    18
3678    24
Name: deteksi_kendaraan, Length: 3679, dtype: int64

In [ ]:
df6_filtered = df6.loc[df6['deteksi_kendaraan'].apply(len) != 2]
df6_filtered

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","['mobil', 'motor', 'truk']",['sedan'],['tewas']
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","['mobil', 'motor']",['sedan'],['tewas']
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",['motor'],['sedan'],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",['motor'],['sedan'],[]
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","['mobil', 'motor', 'truk']",['sedan'],['selamat']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","['mobil', 'truk', 'bus']",['minibus'],['tewas']
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","['mobil', 'truk', 'bus']",['sedan'],['tewas']
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","['mobil', 'truk']",['sedan'],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","['mobil', 'motor']",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","['mobil', 'truk', 'bus']",[],['tewas']

Menghapus yang kira2 memiliki label yang tidak berhubungan :
Sepakbola, detikHealth, detikInet, detikEdu, detikFinance, detikHot

In [ ]:
df6_filtered['label'].value_counts()

detikNews       1175
detikJabar       421
detikJatim       416
detikOto         341
detikJateng      335
detikBali        249
detikSumut       173
detikSulsel      159
detikFinance      38
detikEdu          17
detikHot          10
detikInet          8
detikHealth        6
Sport              2
Sepakbola          1
Name: label, dtype: int64

In [ ]:
df_cek_label = df6_filtered.loc[df6_filtered['label'] == 'detikFinance']
df_cek_label

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
25,6639167,Senin,27,3,2023.0,"Kecelakaan Lalin Kerap Terjadi Saat Mudik, Beg...",Jakarta,detikFinance,Almadinah Putri Brilian,"[""['jakarta',"", ""'-',"", ""'celaka',"", ""'lalu',""...",['pesawat'],[],['selamat']
36,6636887,Sabtu,25,3,2023.0,Kuota Mudik Gratis Jakarta-Semarang Lewat Laut...,Jakarta,detikFinance,Ilyas Fadilah,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'hubung...","['motor', 'kapal']",['sedan'],[]
65,6629129,Senin,20,3,2023.0,Syabda Perkasa Meninggal Kecelakaan di Tol Pem...,Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'syabda',"", ""'perkasa...",['truk'],['sedan'],['tewas']
109,6622916,Kamis,16,3,2023.0,"65 Ribu Kuota Mudik Gratis Dibuka BUMN, Bisa N...",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'bumn',...","['kapal', 'bus', 'kereta']",[],[]
115,6620767,Rabu,15,3,2023.0,"Ada Mudik Gratis BUMN buat 65.603 Orang, Begin...",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'badan'...","['kapal', 'bus', 'kereta']",[],[]
145,6614923,Minggu,12,3,2023.0,"106 Juta Orang Diprediksi Mudik Lebaran 2023, ...",Jakarta,detikFinance,Almadinah Putri Brilian,"[""['jakarta',"", ""'-',"", ""'badan',"", ""'bijak',""...","['mobil', 'motor', 'bus']",[],['selamat']
314,6579324,Senin,20,2,2023.0,"Mudik Motor Gratis Naik Kereta, Pengendaranya ...",Jakarta,detikFinance,Anisa Indraini,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'hubung...","['motor', 'kereta']",[],[]
319,6578559,Senin,20,2,2023.0,"Bye-bye Macet, PUPR Bangun 3 Flyover di Sumsel",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'kerja'...",['kereta'],[],[]
343,6573501,Jumat,17,2,2023.0,Tesla Tarik 362.758 Mobil Listrik Terkait Soft...,Jakarta,detikFinance,Ilyas Fadilah,"[""['jakarta',"", ""'-',"", ""'tesla',"", ""'tarik',""...",['mobil'],['sedan'],['selamat']
424,6557960,Rabu,8,2,2023.0,"Penerapan ERP di DKI Masih Dikaji, Heru Budi: ...",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'pemprov',"", ""'dki',""...","['motor', 'truk']",['sedan'],[]
426,6557901,Rabu,8,2,2023.0,"Terkuak, Ini Alasan Pemprov DKI Mau Terapkan E...",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'pemprov',"", ""'dki',""...","['motor', 'truk']",['sedan'],[]
624,6537356,Jumat,27,1,2023.0,"Hampir Separuh Warga Belum Bayar Pajak, Awas K...",Jakarta,detikFinance,Anisa Indraini,"[""['jakarta',"", ""'-',"", ""'perintah',"", ""'mau',...","['motor', 'bus']",['sedan'],[]
839,6510567,Rabu,11,1,2023.0,"Moge Bisa Masuk Tol di Luar Negeri, Kenapa di ...",Jakarta,detikFinance,Aulia Damayanti,"[""['jakarta',"", ""'-',"", ""'komunitas',"", ""'moto...",['motor'],['sedan'],[]
975,6483940,Selasa,27,12,2022.0,"Mobil Tercebur ke Laut Merak, Gimana Urus Asur...",Jakarta,detikFinance,Aulia Damayanti,"[""['jakarta',"", ""'-',"", ""'baru',"", ""'ini',"", ""...","['mobil', 'kapal', 'bus']",['sedan'],['tewas']
984,6481713,Senin,26,12,2022.0,"Dilarang Wira-wiri 2023, 'Truk Obesitas' Bikin...",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'truk',"", ""'obesitas'...",['truk'],[],[]
992,6480492,Minggu,25,12,2022.0,Menimbang Dampak Penghapusan Truk Obesitas di ...,Jakarta,detikFinance,Anisa Indraini,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'hubung...","['truk', 'kereta']",['sedan'],[]
1170,6435761,Rabu,30,11,2022.0,"Jelang Nataru Jalur Pulau Jawa Mulai Disisir, ...",Jakarta,detikFinance,Ilyas Fadilah,"[""['jakarta',"", ""'-',"", ""'jasa',"", ""'raharja',...",['truk'],[],[]
1283,6412430,Kamis,17,11,2022.0,"RI Ingatkan Potensi Tumpahan Minyak di Laut, S...",Jakarta,detikFinance,Sylke Febrina Laucereno,"[""['jakarta',"", ""'-',"", ""'kapal',"", ""'tanker',...","['kapal', 'bus']",[],['selamat']
1448,6377984,Minggu,30,10,2022.0,"Sempat Tertimbun Longsoran, Jalan Trans Sulawe...",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'menteri',"", ""'kerja'...",['mobil'],[],[]
1570,6355666,Selasa,18,10,2022.0,"Respons Temuan KNKT, Pertamina Beberkan Perawa...",Jakarta,detikFinance,Aulia Damayanti,"[""['jakarta',"", ""'-',"", ""'truk',"", ""'tangki',""...","['mobil', 'truk']",[],['selamat']
1757,6314319,Selasa,27,9,2022.0,"Risiko Usaha Adalah? Berikut Jenis, Contoh dan...",Jakarta,detikFinance,Adelaide Wreta,"[""['jakarta',"", ""'-',"", ""'tiap',"", ""'usaha',"",...",['bus'],[],"['cedera', 'selamat']"
1839,6300615,Senin,19,9,2022.0,"Asap Bikin Tabarakan Maut di Tol, Operator Dim...",Jakarta,detikFinance,Shafira Cendra Arini,"[""['jakarta',"", ""'-',"", ""'perintah',"", ""'lewat...",['mobil'],['sedan'],['selamat']
1881,6296808,Sabtu,17,9,2022.0,"Pak Jokowi, Pejabat Pakai Mobil Listrik Itu Ba...",Jakarta,detikFinance,Sylke Febrina Laucereno,"[""['jakarta',"", ""'-',"", ""'perintah',"", ""'minta...","['mobil', 'motor', 'truk', 'bus']",['sedan'],[]
1887,6295301,Jumat,16,9,2022.0,"Mobil Rawan Ngebut di Tol Trans Sumatera, Oper...",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'tol',"", ""'trans',"", ...","['mobil', 'truk']",[],['selamat']
1889,6294865,Jumat,16,9,2022.0,"Cerita Sopir Truk, Pilih Lewat Tol Trans Sumat...",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'was-was',"", ""'mungki...","['motor', 'truk']",[],[]
1972,6272012,Minggu,4,9,2022.0,"Kecelakaan Truk Masih Marak, Apa Akar Masalahnya?",Jakarta,detikFinance,Achmad Dwi Afriyadi,"[""['jakarta',"", ""'-',"", ""'celaka',"", ""'yang',""...","['truk', 'bus']",['tronton'],[]
2140,6244426,Sabtu,20,8,2022.0,"Fakta-fakta Tol Pemalang-Batang, Lokasi Kecela...",Jakarta,detikFinance,Ilyas Fadilah,"[""['jakarta',"", ""'-',"", ""'mantan',"", ""'wakil',...","['mobil', 'truk']",[],[]
2149,6244376,Sabtu,20,8,2022.0,"Meninggal Dunia, Ini Profil Mantan Wamen PUPR ...",Jakarta,detikFinance,Ilyas Fadilah,"[""['jakarta',"", ""'-',"", ""'mantan',"", ""'wakil',...","['mobil', 'truk', 'bus']",[],[]
2439,6188706,Rabu,20,7,2022.0,"Perhatian! 2 Tahun Tak Bayar Pajak, Mobil dan ...",Jakarta,detikFinance,Fadhly Fauzi Rachman,"[""['jakarta',"", ""'-',"", ""'tim',"", ""'bina',"", ""...","['motor', 'truk', 'bus']",[],['selamat']
2585,6169252,Jumat,8,7,2022.0,"Dibayar Bareng Pajak Kendaraan, Ini Sejumlah M...",Jakarta,detikFinance,Yudistira Imandiar,"[""['jakarta',"", ""'-',"", ""'direktur',"", ""'utama...",['motor'],[],[]
3178,6078798,Minggu,15,5,NaN,"Angka Kecelakaan Turun di Mudik 2022, Ini Sede...",Jakarta,detikFinance,Kholida Qothrunnada,"[""['jakarta',"", ""'-',"", ""'mobilitas',"", ""'arus...","['mobil', 'motor']",[],['selamat']
3403,6053690,Rabu,27,4,2022.0,Kecelakaan KA Lodaya vs Truk Hambat Perjalanan...,Jakarta,detikFinance,Ardan Adhi Chandra,"[""['jakarta',"", ""'-',"", ""'jalan',"", ""'kereta',...","['truk', 'kereta']",[],['selamat']
3450,6048235,Minggu,24,4,2022.0,"Pesan MUI untuk Pemudik Lewat Tol: Sabar, Jang...",Jakarta,detikFinance,Kholida Qothrunnada,"[""['jakarta',"", ""'-',"", ""'majelis',"", ""'ulama'...",['bus'],[],['selamat']
3452,6048042,Minggu,24,4,2022.0,"Please...Jangan Nekat Mudik Pakai Motor, Bahaya!",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'risiko',"", ""'celaka'...","['mobil', 'motor', 'truk', 'pesawat', 'kapal',...",['sedan'],[]
3485,6043772,Kamis,21,4,2022.0,"Terabas Rel Saat Kereta Lewat, Pengemudi Bisa ...",Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'celaka',"", ""'pada',""...","['mobil', 'motor', 'kereta']",['sedan'],['selamat']
3487,6043686,Kamis,21,4,2022.0,KAI Mau Tuntut Pengemudi Mobil yang Tertabarak...,Jakarta,detikFinance,Herdi Alif Al Hikam,"[""['jakarta',"", ""'-',"", ""'pt',"", ""'kereta',"", ...","['mobil', 'kereta']",[],['selamat']
3503,6042202,Rabu,20,4,2022.0,"Kecelakaan KRL Vs Mobil, KAI Akan Laporkan dan...",Jakarta,detikFinance,Ardan Adhi Chandra,"[""['jakarta',"", ""'-',"", ""'buntut',"", ""'celaka'...","['mobil', 'kereta']",[],['selamat']
3513,6040742,Selasa,19,4,2022.0,"1.900 Km Tol Era Jokowi, Ini Potensi Ekonomi d...",Jakarta,detikFinance,Ignacio Geordi Oswaldo,"[""['jakarta',"", ""'-',"", ""'ketua',"", ""'urus',"",...",['truk'],[],[]

menghapus baris yang mempunyai label tertentu

In [ ]:
df6_filtered_2 = df6_filtered[~df6_filtered['label'].isin(['Sepakbola', 'detikHealth', 'detikEdu', 'detikFinance', 'Sport', 'detikInet', 'detikHot'])]
df6_filtered_2

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","['mobil', 'motor', 'truk']",['sedan'],['tewas']
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","['mobil', 'motor']",['sedan'],['tewas']
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",['motor'],['sedan'],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",['motor'],['sedan'],[]
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","['mobil', 'motor', 'truk']",['sedan'],['selamat']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","['mobil', 'truk', 'bus']",['minibus'],['tewas']
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","['mobil', 'truk', 'bus']",['sedan'],['tewas']
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","['mobil', 'truk']",['sedan'],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","['mobil', 'motor']",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","['mobil', 'truk', 'bus']",[],['tewas']

In [ ]:
df6_filtered_2['label'].value_counts()

detikNews      1175
detikJabar      421
detikJatim      416
detikOto        341
detikJateng     335
detikBali       249
detikSumut      173
detikSulsel     159
Name: label, dtype: int64

Mengubah list menjadi string

In [ ]:
df6_filtered_3 = df6_filtered_2['deteksi_kendaraan'].apply(lambda x: str(x).strip('[]').replace("'", ""))

# df6_filtered_3 = [', '.join(map(str, row)).replace('[','').replace(']','').replace("'", "") for row in df6_filtered_2['deteksi_kendaraan']]

df6_filtered_3

0       mobil, motor, truk
1             mobil, motor
3                    motor
4                    motor
5       mobil, motor, truk
               ...
3674      mobil, truk, bus
3675      mobil, truk, bus
3676           mobil, truk
3677          mobil, motor
3678      mobil, truk, bus
Name: deteksi_kendaraan, Length: 3269, dtype: object

In [ ]:
df6_filtered_3_next = pd.DataFrame(df6_filtered_3)
df6_filtered_3_next

       deteksi_kendaraan
0     mobil, motor, truk
1           mobil, motor
3                  motor
4                  motor
5     mobil, motor, truk
...                  ...
3674    mobil, truk, bus
3675    mobil, truk, bus
3676         mobil, truk
3677        mobil, motor
3678    mobil, truk, bus

[3269 rows x 1 columns]

In [ ]:
all_kendaraan = []
for i in df6_filtered_3_next['deteksi_kendaraan']:
    all_kendaraan.extend(i.split(', '))

# menghitung jumlah kemunculan setiap kendaraan
kendaraan_counts = pd.Series(all_kendaraan).value_counts()

print(kendaraan_counts)

mobil      2023
motor      1718
truk       1606
bus         905
kereta      179
kapal        52
pesawat      43
perahu       16
dtype: int64

In [ ]:
df6_filtered_2['deteksi_kendaraan'] = df6_filtered_3_next
df6_filtered_2

<ipython-input-22-3ca0bffb3717>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6_filtered_2['deteksi_kendaraan'] = df6_filtered_3_next

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","mobil, motor, truk",['sedan'],['tewas']
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","mobil, motor",['sedan'],['tewas']
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",motor,['sedan'],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",motor,['sedan'],[]
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","mobil, motor, truk",['sedan'],['selamat']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","mobil, truk, bus",['minibus'],['tewas']
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","mobil, truk, bus",['sedan'],['tewas']
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","mobil, truk",['sedan'],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","mobil, motor",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","mobil, truk, bus",[],['tewas']

In [ ]:
df6_filtered_2

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","mobil, motor, truk",['sedan'],['tewas']
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","mobil, motor",['sedan'],['tewas']
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",motor,['sedan'],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",motor,['sedan'],[]
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","mobil, motor, truk",['sedan'],['selamat']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","mobil, truk, bus",['minibus'],['tewas']
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","mobil, truk, bus",['sedan'],['tewas']
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","mobil, truk",['sedan'],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","mobil, motor",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","mobil, truk, bus",[],['tewas']

In [ ]:
# membuat mask untuk baris yang mengandung string "pesawat", "kapal", atau "perahu"
mask = df6_filtered_2['deteksi_kendaraan'].str.contains('pesawat|kapal|perahu')

# menghilangkan baris yang memenuhi kriteria
df6_filtered_4 = df6_filtered_2[~mask]
df6_filtered_4

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","mobil, motor, truk",['sedan'],['tewas']
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","mobil, motor",['sedan'],['tewas']
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",motor,['sedan'],[]
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",motor,['sedan'],[]
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","mobil, motor, truk",['sedan'],['selamat']
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","mobil, truk, bus",['minibus'],['tewas']
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","mobil, truk, bus",['sedan'],['tewas']
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","mobil, truk",['sedan'],[]
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","mobil, motor",[],[]
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","mobil, truk, bus",[],['tewas']

In [ ]:
all_kendaraan = []
for i in df6_filtered_4['deteksi_kendaraan']:
    all_kendaraan.extend(i.split(', '))

# menghitung jumlah kemunculan setiap kendaraan
kendaraan_counts = pd.Series(all_kendaraan).value_counts()

print(kendaraan_counts)

mobil     1975
motor     1680
truk      1564
bus        878
kereta     168
dtype: int64

In [ ]:
df_model_string = df6_filtered_4['model_kendaraan'].apply(lambda x: str(x).strip('[]').replace("'", ""))
df_kondisi_string = df6_filtered_4['kondisi'].apply(lambda x: str(x).strip('[]').replace("'", ""))

df_model_string

0         sedan
1         sedan
3         sedan
4         sedan
5         sedan
         ...
3674    minibus
3675      sedan
3676      sedan
3677
3678
Name: model_kendaraan, Length: 3162, dtype: object

In [ ]:
df_model_new = pd.DataFrame(df_model_string)
df_model_new

     model_kendaraan
0              sedan
1              sedan
3              sedan
4              sedan
5              sedan
...              ...
3674         minibus
3675           sedan
3676           sedan
3677
3678

[3162 rows x 1 columns]

In [ ]:
df_kondisi_new = pd.DataFrame(df_kondisi_string)
df_kondisi_new

      kondisi
0       tewas
1       tewas
3
4
5     selamat
...       ...
3674    tewas
3675    tewas
3676
3677
3678    tewas

[3162 rows x 1 columns]

In [ ]:
df7 = df6_filtered_4
df7['model_kendaraan'] = df_model_new
df7['kondisi'] = df_kondisi_new

<ipython-input-29-e850c04741a7>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['model_kendaraan'] = df_model_new
<ipython-input-29-e850c04741a7>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7['kondisi'] = df_kondisi_new

In [ ]:
df7

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","mobil, motor, truk",sedan,tewas
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","mobil, motor",sedan,tewas
3,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",motor,sedan,
4,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",motor,sedan,
5,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","mobil, motor, truk",sedan,selamat
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3674,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","mobil, truk, bus",minibus,tewas
3675,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","mobil, truk, bus",sedan,tewas
3676,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","mobil, truk",sedan,
3677,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","mobil, motor",,
3678,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","mobil, truk, bus",,tewas

### Bismillah hasil akhir

In [ ]:
df7.to_csv('final_result_kasar.csv', index=False)
files.download('final_result_kasar.csv')

In [ ]:
df8_ver1 = pd.read_csv('final_result_kasar.csv')
df8_ver1['model_kendaraan'] = df8_ver1['model_kendaraan'].fillna('tidak_ada_data')
df8_ver1['kondisi'] = df8_ver1['kondisi'].fillna('tidak_ada_data')

In [ ]:
df8_ver1

,id,hari,tanggal,bulan,tahun,judul,kota,label,penulis,deskripsi,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,detikJabar,Tim detikJabar,"[""['bandung',"", ""'-',"", ""'agam',"", ""'peristiwa...","mobil, motor, truk",sedan,tewas
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,detikSumut,Ferdi Almunanda,"[""['jambi',"", ""'-',"", ""'abg',"", ""'nama',"", ""'s...","mobil, motor",sedan,tewas
2,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,detikJatim,Deny Prastyo,"[""['surabaya',"", ""'-',"", ""'polisi',"", ""'telah'...",motor,sedan,tidak_ada_data
3,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,detikJabar,Rifat Alhamidi,"[""['bandung',"", ""'-',"", ""'polisi',"", ""'pasti',...",motor,sedan,tidak_ada_data
4,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'viral',"", ""'di',"", ""...","mobil, motor, truk",sedan,selamat
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3157,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,detikJateng,Tim detikJateng,"[""['solo',"", ""'-',"", ""'celaka',"", ""'maut',"", ""...","mobil, truk, bus",minibus,tewas
3158,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,detikJateng,Angling Adhitya Purbaya,"[""['semarang',"", ""'-',"", ""'celaka',"", ""'adu',""...","mobil, truk, bus",sedan,tewas
3159,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,detikOto,Tim detikcom,"[""['jakarta',"", ""'-',"", ""'batas',"", ""'cepat',""...","mobil, truk",sedan,tidak_ada_data
3160,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,detikOto,Dina Rayanti,"[""['jakarta',"", ""'-',"", ""'produsen',"", ""'asal'...","mobil, motor",tidak_ada_data,tidak_ada_data
3161,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,detikNews,Tim detikcom,"[""['malang',"", ""'-',"", ""'banyak',"", ""'5',"", ""'...","mobil, truk, bus",tidak_ada_data,tewas

In [ ]:
df8_ver1.drop(columns=['label', 'penulis', 'deskripsi'], inplace=True)
df8_ver1

,id,hari,tanggal,bulan,tahun,judul,kota,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,"mobil, motor, truk",sedan,tewas
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,"mobil, motor",sedan,tewas
2,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,motor,sedan,tidak_ada_data
3,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,motor,sedan,tidak_ada_data
4,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,"mobil, motor, truk",sedan,selamat
...,...,...,...,...,...,...,...,...,...,...
3157,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,"mobil, truk, bus",minibus,tewas
3158,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,"mobil, truk, bus",sedan,tewas
3159,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,"mobil, truk",sedan,tidak_ada_data
3160,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,"mobil, motor",tidak_ada_data,tidak_ada_data
3161,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,"mobil, truk, bus",tidak_ada_data,tewas

In [ ]:
df8_ver2 = pd.read_csv('final_result_kasar.csv')
df8_ver2.drop(columns=['label', 'penulis', 'deskripsi'], inplace=True)
df8_ver2

,id,hari,tanggal,bulan,tahun,judul,kota,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,"mobil, motor, truk",sedan,tewas
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,"mobil, motor",sedan,tewas
2,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,motor,sedan,NaN
3,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,motor,sedan,NaN
4,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,"mobil, motor, truk",sedan,selamat
...,...,...,...,...,...,...,...,...,...,...
3157,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,"mobil, truk, bus",minibus,tewas
3158,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,"mobil, truk, bus",sedan,tewas
3159,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,"mobil, truk",sedan,NaN
3160,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,"mobil, motor",NaN,NaN
3161,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,"mobil, truk, bus",NaN,tewas

In [ ]:
df8_ver1.to_csv('final_result_version1.csv', index=False)
files.download('final_result_version1.csv')
df8_ver1.to_csv('final_result_version2.csv', index=False)
files.download('final_result_version2.csv')

### Melihat data yang terbanyak (perkolom)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving final_result_version1.csv to final_result_version1 (1).csv

In [ ]:
df_final_count = pd.read_csv('final_result_version1.csv')
df_final_count

,id,hari,tanggal,bulan,tahun,judul,kota,deteksi_kendaraan,model_kendaraan,kondisi
0,6646815,Kamis,30,3,2023.0,Jabar Hari Ini: Sakit Hati Dua Pemain Muda Persib,Bandung,"mobil, motor, truk",sedan,tewas
1,6647430,Kamis,30,3,2023.0,Waka DPRD Tanjabbar Tinggalkan TKP Usai Mobil ...,Jambi,"mobil, motor",sedan,tewas
2,6647008,Kamis,30,3,2023.0,Pemotor Mabuk Tabrak 3 Anggota Satpol PP Surab...,Surabaya,motor,sedan,tidak_ada_data
3,6646405,Kamis,30,3,2023.0,Fakta Viral Pria Tergeletak dengan Wajah Tersa...,Bandung,motor,sedan,tidak_ada_data
4,6646302,Kamis,30,3,2023.0,Aksi Nekat Pemotor Blayer-Potong Konvoi Presid...,Jakarta,"mobil, motor, truk",sedan,selamat
...,...,...,...,...,...,...,...,...,...,...
3157,6012255,Jumat,1,4,2022.0,Fakta-fakta Kecelakaan Adu Banteng Tewaskan 5 ...,Solo,"mobil, truk, bus",minibus,tewas
3158,6012252,Jumat,1,4,2022.0,Jasa Raharja Pati Cairkan Santunan 3 Korban Ke...,Semarang,"mobil, truk, bus",sedan,tewas
3159,6012027,Jumat,1,4,2022.0,"Jangan Lelet Apalagi Ngebut di Tol, Segini Bat...",Jakarta,"mobil, truk",sedan,tidak_ada_data
3160,6011922,Jumat,1,4,2022.0,Hyundai Ioniq 5 Tambah Daftar Mobil yang Kebal...,Jakarta,"mobil, motor",tidak_ada_data,tidak_ada_data
3161,6011711,Jumat,1,4,2022.0,Detik-detik Kecelakaan Adu Banteng yang Tewask...,Pemalang,"mobil, truk, bus",tidak_ada_data,tewas

### **Bulan Terbanyak**

In [ ]:
bulan_counts = df_final_count['bulan'].value_counts()
print(bulan_counts)

7     326
1     323
5     322
6     280
2     278
10    261
9     258
4     251
11    239
8     223
12    204
3     197
Name: bulan, dtype: int64

In [ ]:
import calendar
import pandas as pd

# Hitung jumlah data untuk setiap bulan
bulan_count = df_final_count['bulan'].value_counts()

# Buat dictionary untuk kolom-kolom baru
new_cols = {'bulan': bulan_count.index,
            'count': bulan_count.values,
            'nama_bulan': [calendar.month_name[bulan] for bulan in bulan_count.index]}

# Buat dataframe baru dari dictionary
df_bulan = pd.DataFrame(new_cols)

# Urutkan dataframe berdasarkan bulan
df_bulan = df_bulan.sort_values('bulan')

# Reset index dataframe
df_bulan = df_bulan.reset_index(drop=True)

In [ ]:
df_bulan

    bulan  count nama_bulan
0       1    323    January
1       2    278   February
2       3    197      March
3       4    251      April
4       5    322        May
5       6    280       June
6       7    326       July
7       8    223     August
8       9    258  September
9      10    261    October
10     11    239   November
11     12    204   December

In [ ]:
df_bulan.to_csv('final_count_bulan.csv', index=False)
files.download('final_count_bulan.csv')

### Kota Terbanyak

In [ ]:
kota_counts = df_final_count['kota'].value_counts()

kota_counts = {'kota': kota_counts.index,
            'count': kota_counts.values}

In [ ]:
df_kota = pd.DataFrame(kota_counts)
df_kota

              kota  count
0          Jakarta   1191
1          Bandung    121
2         Surabaya    110
3            Bogor     90
4           Bekasi     67
..             ...    ...
211           Peru      1
212         Negara      1
213  Kota Pasuruan      1
214   Tanjungbalai      1
215     Banda Aceh      1

[216 rows x 2 columns]

In [ ]:
df_kota.to_csv('final_count_kota.csv', index=False)
files.download('final_count_kota.csv')

### data jenis kendaraan

In [ ]:
all_kendaraan = []
for i in df_final_count['deteksi_kendaraan']:
    all_kendaraan.extend(i.split(', '))

# menghitung jumlah kemunculan setiap kendaraan
kendaraan_counts = pd.Series(all_kendaraan).value_counts()

print(kendaraan_counts)

mobil     1975
motor     1680
truk      1564
bus        878
kereta     168
dtype: int64

In [ ]:
kendaraan_counts = {'kendaraan': kendaraan_counts.index,
            'count': kendaraan_counts.values}

df_kendaraan = pd.DataFrame(kendaraan_counts)
df_kendaraan

  kendaraan  count
0     mobil   1975
1     motor   1680
2      truk   1564
3       bus    878
4    kereta    168

In [ ]:
df_kendaraan.to_csv('final_count_kendaraan.csv', index=False)
files.download('final_count_kendaraan.csv')

### Data Model kendaraan

In [ ]:
all_model = []
for i in df_final_count['model_kendaraan']:
    all_model.extend(i.split(', '))

# menghitung jumlah kemunculan setiap kendaraan
model_counts = pd.Series(all_model).value_counts()

print(model_counts)

tidak_ada_data    1555
sedan             1251
minibus            204
pikap              171
tronton            127
kontainer           85
angkot              71
taksi               48
jeep                 9
mikrolet             3
dtype: int64

In [ ]:
model_counts = {'model_kendaraan': model_counts.index,
            'count': model_counts.values}

df_model = pd.DataFrame(model_counts)
df_model

  model_kendaraan  count
0  tidak_ada_data   1555
1           sedan   1251
2         minibus    204
3           pikap    171
4         tronton    127
5       kontainer     85
6          angkot     71
7           taksi     48
8            jeep      9
9        mikrolet      3

In [ ]:
df_model.to_csv('final_count_model.csv', index=False)
files.download('final_count_model.csv')

### Data Kondisi

In [ ]:
all_kondisi = []
for i in df_final_count['kondisi']:
    all_kondisi.extend(i.split(', '))

# menghitung jumlah kemunculan setiap kendaraan
kondisi_counts = pd.Series(all_kondisi).value_counts()

print(kondisi_counts)

tewas             1539
tidak_ada_data    1141
selamat            740
cedera              79
kritis              49
meninggal           44
terluka             44
dtype: int64

In [ ]:
kondisi_counts = {'kondisi': kondisi_counts.index,
            'count': kondisi_counts.values}

df_kondisi = pd.DataFrame(kondisi_counts)
df_kondisi

          kondisi  count
0           tewas   1539
1  tidak_ada_data   1141
2         selamat    740
3          cedera     79
4          kritis     49
5       meninggal     44
6         terluka     44

In [ ]:
df_kondisi.to_csv('final_count_kondisi.csv', index=False)
files.download('final_count_kondisi.csv')

### Udahan ah Cape